Q1:
    
+ Decrease C. 
+ Decrease sigma. 

Q2:
    
+ Use an SVM with a Gaussian kernel.
+ Use a logistic regression model including additional quadratic features. 

Q3:
-2

Q4:
-2

Q5:

+ The maximum value of a Gaussian kernel is 1.
+ Suppose we use a (binary) SVM to classify the digits data (that have 10 classes) using the one-vs-one approach. Then we need to train 45 SVMs.


Q6
888

Q7
291

Q8
14

Q9
868

Q10
288
    
Q11
14

Q12
860
    
Q13
291

Q14
14

Q15
Number of SVs: 1241
    
Q16
Train Errors: 232

Q17
Test Errors: 14

Q18
Number of SVs: 1009
    
Q19
Train Errors: 146

Q20
Test Errors: 15

Q21
Number of SVs: 965
    
Q22
Train Errors: 90

Q23
Test Errors: 17

In [1]:
import numpy as np
import pandas as pd

from sklearn.naive_bayes import  GaussianNB
from sklearn.metrics import confusion_matrix

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [33]:
url = "https://liangfgithub.github.io/Data/spam.txt"
spam = pd.read_table(url, sep="\s+", header=None)
spam

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.000,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.010,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4596,0.31,0.00,0.62,0.0,0.00,0.31,0.00,0.00,0.00,0.00,...,0.000,0.232,0.0,0.000,0.000,0.000,1.142,3,88,0
4597,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.353,0.000,0.000,1.555,4,14,0
4598,0.30,0.00,0.30,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.102,0.718,0.0,0.000,0.000,0.000,1.404,6,118,0
4599,0.96,0.00,0.00,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.000,0.057,0.0,0.000,0.000,0.000,1.147,5,78,0
4600,0.00,0.00,0.65,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.125,0.000,0.000,1.250,5,40,0

In [32]:
spam_test = pd.concat([spam[0:100], spam[1900:1960]])
spam_train = pd.concat([spam[100:1900], spam[1960:]])

print("spam.shape=", spam.shape)
print("spam_test.shape=", spam_test.shape)
print("spam_train.shape=", spam_train.shape)

spam.shape= (4601, 58)
spam_test.shape= (160, 58)
spam_train.shape= (4441, 58)

In [36]:
spam_test.head()

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1

In [1]:
from sklearn.svm import LinearSVC

In [5]:
import pandas as pd
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
import numpy as np

# Load the dataset
url = "https://liangfgithub.github.io/Data/spam.txt"
spam = pd.read_table(url, sep="\s+", header=None)

testID = list(range(0, 100)) + list(range(1900, 1960))
spam_test = spam.loc[testID, :]
spam_train = spam.drop(testID)
X = spam_train.drop(57, axis=1)
y = spam_train[57]
Xtest = spam_test.drop(57, axis=1)
ytest = spam_test[57]

sc = StandardScaler()
sc.fit(X)
sc.scale_ = np.std(X, axis=0, ddof=1).to_list()
newX = sc.transform(X)
newXtest = sc.transform(Xtest)

In [9]:
def process_linear_svc(cost):
    clf = SVC(kernel='linear', C=cost)
    clf.fit(newX, y)

    print(f"cost: {cost}")
    
    y_pred = clf.predict(newX)
    ctable_train = confusion_matrix(y, y_pred)
    print(f"Train-Confusion-Matrix={ctable_train}")

    ytest_pred = clf.predict(newXtest)
    ctable_test = confusion_matrix(ytest, ytest_pred)
    print(f"Test-Confusion-Matrix={ctable_test}")

    num_SVs = sum(clf.n_support_)
    print(f"Number of SVs: {num_SVs}")
    print(f"Train Errors: {ctable_train[0, 1] + ctable_train[1, 0]}")
    print(f"Test Errors: {ctable_test[0, 1] + ctable_test[1, 0]}")

In [10]:
process_linear_svc(cost = 1)

cost: 1
Train-Confusion-Matrix=[[2616  112]
 [ 179 1534]]
Test-Confusion-Matrix=[[58  2]
 [12 88]]
Number of SVs: 888
Train Errors: 291
Test Errors: 14

In [11]:
process_linear_svc(cost = 10)

cost: 10
Train-Confusion-Matrix=[[2618  110]
 [ 178 1535]]
Test-Confusion-Matrix=[[57  3]
 [11 89]]
Number of SVs: 868
Train Errors: 288
Test Errors: 14

In [12]:
process_linear_svc(cost = 50)

cost: 50
Train-Confusion-Matrix=[[2616  112]
 [ 179 1534]]
Test-Confusion-Matrix=[[57  3]
 [11 89]]
Number of SVs: 860
Train Errors: 291
Test Errors: 14

In [15]:
def process_gaussian_svc(cost):
    clf = SVC(kernel='rbf', C=cost)
    clf.fit(newX, y)

    print(f"cost: {cost}")
    
    y_pred = clf.predict(newX)
    ctable_train = confusion_matrix(y, y_pred)
    print(f"Train-Confusion-Matrix={ctable_train}")

    ytest_pred = clf.predict(newXtest)
    ctable_test = confusion_matrix(ytest, ytest_pred)
    print(f"Test-Confusion-Matrix={ctable_test}")

    num_SVs = sum(clf.n_support_)
    print(f"Number of SVs: {num_SVs}")
    print(f"Train Errors: {ctable_train[0, 1] + ctable_train[1, 0]}")
    print(f"Test Errors: {ctable_test[0, 1] + ctable_test[1, 0]}")

In [16]:
process_gaussian_svc(cost = 1)

cost: 1
Train-Confusion-Matrix=[[2643   85]
 [ 147 1566]]
Test-Confusion-Matrix=[[56  4]
 [10 90]]
Number of SVs: 1241
Train Errors: 232
Test Errors: 14

In [19]:
process_gaussian_svc(cost = 10)

cost: 10
Train-Confusion-Matrix=[[2681   47]
 [  99 1614]]
Test-Confusion-Matrix=[[57  3]
 [11 89]]
Number of SVs: 1009
Train Errors: 146
Test Errors: 14

In [18]:
process_gaussian_svc(cost = 50)

cost: 50
Train-Confusion-Matrix=[[2701   27]
 [  63 1650]]
Test-Confusion-Matrix=[[57  3]
 [14 86]]
Number of SVs: 965
Train Errors: 90
Test Errors: 17