In [1]:
import numpy as np
import pandas as pd
from matplotlib.pyplot import subplots

import statsmodels.api as sm

from statsmodels.stats.outliers_influence import variance_inflation_factor as VIF
from statsmodels.stats.anova import anova_lm

from ISLP import load_data
from ISLP.models import (ModelSpec as MS,
                         summarize,
                         poly)

# Q1-Q3

In [2]:
Auto = load_data('Auto')
Auto.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name'],
      dtype='object')

In [3]:
print(Auto.shape)
Auto

(392, 9)

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
387,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
389,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
390,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
391,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [4]:
Auto.describe().iloc[:,:4]

              mpg   cylinders  displacement  horsepower
count  392.000000  392.000000    392.000000  392.000000
mean    23.445918    5.471939    194.411990  104.469388
std      7.805007    1.705783    104.644004   38.491160
min      9.000000    3.000000     68.000000   46.000000
25%     17.000000    4.000000    105.000000   75.000000
50%     22.750000    4.000000    151.000000   93.500000
75%     29.000000    8.000000    275.750000  126.000000
max     46.600000    8.000000    455.000000  230.000000

In [5]:
X = pd.DataFrame({'intercept': np.ones(Auto.shape[0]),
                  'displacement': Auto['displacement']})

X = MS(['displacement']).fit_transform(Auto)

#print(type(Auto))
# X=Auto[['displacement']]
# X['intercept']=1

X[:4]

   intercept  displacement
0        1.0         307.0
1        1.0         350.0
2        1.0         318.0
3        1.0         304.0

In [6]:
y = Auto['mpg']
model = sm.OLS(y, X)
results = model.fit()

In [7]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.648
Model:                            OLS   Adj. R-squared:                  0.647
Method:                 Least Squares   F-statistic:                     718.7
Date:                Sat, 16 Sep 2023   Prob (F-statistic):           1.66e-90
Time:                        22:49:53   Log-Likelihood:                -1156.4
No. Observations:                 392   AIC:                             2317.
Df Residuals:                     390   BIC:                             2325.
Df Model:                           1
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
intercept       35.1206      0.494     71.033      0.000      34.149      36.093
displacement    -0.0601      0.002    -26.808      0.000      -0.064      -0.056
==============================================================================
Omnibus:                       41.308   Durbin-Watson:                   0.926
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               61.139
Skew:                           0.709   Prob(JB):                     5.30e-14
Kurtosis:                       4.317   Cond. No.                         466.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [8]:
# Q1

round(results.params['displacement'], 2)

-0.06

In [9]:
# Q2

round(results.rsquared, 2)

0.65

In [10]:
terms = Auto.columns.drop(['name', 'mpg'])
print(terms)
X = MS(terms).fit_transform(Auto)

X[:4]

Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
       'year', 'origin'],
      dtype='object')

,intercept,cylinders,displacement,horsepower,weight,acceleration,year,origin
0,1.0,8,307.0,130,3504,12.0,70,1
1,1.0,8,350.0,165,3693,11.5,70,1
2,1.0,8,318.0,150,3436,11.0,70,1
3,1.0,8,304.0,150,3433,12.0,70,1

In [11]:
model2 = sm.OLS(y, X)
results2 = model2.fit()

In [12]:
results2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.821
Model:                            OLS   Adj. R-squared:                  0.818
Method:                 Least Squares   F-statistic:                     252.4
Date:                Sat, 16 Sep 2023   Prob (F-statistic):          2.04e-139
Time:                        22:49:53   Log-Likelihood:                -1023.5
No. Observations:                 392   AIC:                             2063.
Df Residuals:                     384   BIC:                             2095.
Df Model:                           7
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
intercept      -17.2184      4.644     -3.707      0.000     -26.350      -8.087
cylinders       -0.4934      0.323     -1.526      0.128      -1.129       0.142
displacement     0.0199      0.008      2.647      0.008       0.005       0.035
horsepower      -0.0170      0.014     -1.230      0.220      -0.044       0.010
weight          -0.0065      0.001     -9.929      0.000      -0.008      -0.005
acceleration     0.0806      0.099      0.815      0.415      -0.114       0.275
year             0.7508      0.051     14.729      0.000       0.651       0.851
origin           1.4261      0.278      5.127      0.000       0.879       1.973
==============================================================================
Omnibus:                       31.906   Durbin-Watson:                   1.309
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               53.100
Skew:                           0.529   Prob(JB):                     2.95e-12
Kurtosis:                       4.460   Cond. No.                     8.59e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.59e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [13]:
# Q3
round(results2.params['displacement'], 2)

0.02

# Q4-Q21

In [14]:
beta = np.array([[50, 20, .07, 35, .01, -10]])
beta = np.transpose(beta)

In [15]:
#Q4

X0 = 1
X1 = 4
X2 = 100
X3 = 1
X4 = X1 * X2
X5 = X1 * X3

X = np.array([[X0, X1, X2, X3, X4, X5]])
y = np.matmul(X, beta)

print(y)

[[136.]]

# Q5

# 50 + 20 X1 + .07 X2 + 35 X3 + .01 X1*X2 -10 X1*X3

# Female: 50 + 20 X1 + .07 X2 + 35 + .01 X1*X2 - 10 X1

# Female: 50 + 35 + 10 GPA + .07 IQ + .01 GPA*IQ

85 + 10 GPA + .07 IQ + .01 GPA*IQ

10 X1 + 35

#   Male: 50 + 20 GPA + .07 IQ + .01 GPA*IQ

20 X1

Ans: 
Females earn more, GPA < 3.5
Males earn more, GPA > 3.5

#Q6

Ans: b2, b4 => 7 & 1

# Q7 
85

#Q8
10

#Q9
.07

#Q10
.01

#Q11
50

#Q12
20

#Q13
.07

#Q14
.01

F: 
85 + 10 GPA + .07 IQ + .01 GPA*IQ


M: 
50 + 20 GPA + .07 IQ + .01 GPA*IQ
50 + 20 GPA + .07 IQ + a + .01 GPA*IQ + b GPA
85 + 10 GPA + .07 IQ - 35  + .01 GPA*IQ + 10 GPA



#Q15
85

#Q16
10

#Q17
.07

#Q18
-35

#Q19
.01

#Q20
10

#Q21
RSS decrease
R-square increase

#Q22
LS Coeff
R-Sq

#Q23
linear dependent
n by P
Non-Intercept Predictor

#Q24
It must be zero if we also center X

#Q25
LS Coeff
RSS

#Q26
1